root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/audit-zip"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  exclude_regex = ["_test\\.go"]
  log = "tmp/build.log"
  stop_on_error = true

[log]
  time = false
